/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apps;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class Gui extends javax.swing.JFrame {

    private ServerSocket ss;
    private PrintWriter pw;
    private String oldMsg = "";

    /**
     * Creates new form Gui
     */
    public Gui() {
        try {
            initComponents();          
            ss = new ServerSocket(3030);
            Socket s = ss.accept();          
            pw = new PrintWriter(s.getOutputStream(), true);
        } catch (IOException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelControles = new javax.swing.JPanel();
        jButtonControlesLeft = new javax.swing.JButton();
        jButtonControlesUp = new javax.swing.JButton();
        jButtonControlesRight = new javax.swing.JButton();
        jButtonControlesDown = new javax.swing.JButton();
        jPanelTop = new javax.swing.JPanel();
        jToggleButtonLuz = new javax.swing.JToggleButton();
        jButtonClaxon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Android Conectado!!!");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelControles.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));
        jPanelControles.setLayout(new java.awt.GridBagLayout());

        jButtonControlesLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfx/left_arrow.png"))); // NOI18N
        jButtonControlesLeft.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonPulsado(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonLiberado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 3;
        jPanelControles.add(jButtonControlesLeft, gridBagConstraints);

        jButtonControlesUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfx/up_arrow.png"))); // NOI18N
        jButtonControlesUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonPulsado(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonLiberado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 3;
        jPanelControles.add(jButtonControlesUp, gridBagConstraints);

        jButtonControlesRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfx/right_arrow.png"))); // NOI18N
        jButtonControlesRight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonPulsado(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonLiberado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 3;
        jPanelControles.add(jButtonControlesRight, gridBagConstraints);

        jButtonControlesDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gfx/down_arrow.png"))); // NOI18N
        jButtonControlesDown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonPulsado(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonLiberado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 3;
        jPanelControles.add(jButtonControlesDown, gridBagConstraints);

        getContentPane().add(jPanelControles, java.awt.BorderLayout.CENTER);

        jPanelTop.setBorder(javax.swing.BorderFactory.createTitledBorder("Comandos"));
        jPanelTop.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jToggleButtonLuz.setText("Luces");
        jToggleButtonLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLuzActionPerformed(evt);
            }
        });
        jPanelTop.add(jToggleButtonLuz);

        jButtonClaxon.setText("Claxon");
        jButtonClaxon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClaxonActionPerformed(evt);
            }
        });
        jPanelTop.add(jButtonClaxon);

        getContentPane().add(jPanelTop, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void botonPulsado(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonPulsado
        String s = null;

        switch (evt.getKeyChar()) {
            case '8':
                s = "AD"; //ADELANTE";
                break;
            case '4':
                s = "IZ"; //IZQUIERDA";
                break;
            case '6':
                s = "DER"; //DERECHA";
                break;
            case '5':
                s = "AT"; //ATRAS";
                break;
        }

        if (!oldMsg.equals(s)) { // Solo enviamos los cambios
            pw.println(s);
        }
        oldMsg = s;


    }//GEN-LAST:event_botonPulsado

    private void botonLiberado(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonLiberado
        pw.println("ST");
        oldMsg = "ST";
    }//GEN-LAST:event_botonLiberado

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            pw.close();
            ss.close();
        } catch (IOException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButtonClaxonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClaxonActionPerformed
        pw.println("CL");
        oldMsg = "CL";
    }//GEN-LAST:event_jButtonClaxonActionPerformed

    private void jToggleButtonLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLuzActionPerformed
        if (jToggleButtonLuz.isSelected()) {
            pw.println("LU1");
            oldMsg = "LU1";
        } else {
            pw.println("LU0");
            oldMsg = "LU1";
        }
    }//GEN-LAST:event_jToggleButtonLuzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClaxon;
    private javax.swing.JButton jButtonControlesDown;
    private javax.swing.JButton jButtonControlesLeft;
    private javax.swing.JButton jButtonControlesRight;
    private javax.swing.JButton jButtonControlesUp;
    private javax.swing.JPanel jPanelControles;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JToggleButton jToggleButtonLuz;
    // End of variables declaration//GEN-END:variables
}
